project_id = "wzdlhukymsjittdyuddr"

[functions.send-course-inquiry]
verify_jwt = false

[functions.send-order-notification]
verify_jwt = false

[functions.send-contact-message]
verify_jwt = false

[functions.send-meeting-request]
verify_jwt = false

[functions.send-trainer-application]
verify_jwt = false

[functions.send-junior-inquiry]
verify_jwt = false