import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'en' | 'ro' | 'ru';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string, defaultValue?: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Translation data
const translations: Record<Language, Record<string, string>> = {
  en: {
    // Navigation
    'nav.courses': 'Courses',
    'nav.about': 'About',
    'nav.trainers': 'Trainers',
    'nav.blog': 'Blog',
    'nav.hardware': 'Hardware',
    'nav.contact': 'Contact',
    'nav.login': 'Login',
    'nav.getStarted': 'Get Started',
    
    // Hero Section
    'hero.title': 'Engineers Factory - Embedded School',
    'hero.subtitle': 'Build Your Future',
    'hero.description': 'Join thousands of students mastering cutting-edge technology through hands-on courses in IoT, embedded systems, and more.',
    'hero.startLearning': 'Start Learning Today',
    'hero.watchDemo': 'Watch Demo',
    'hero.satisfaction': 'Satisfaction Rate',
    'hero.activeStudents': 'Active Students',
    'hero.expertCourses': 'Expert Courses',
    
    // Featured Courses
    'courses.featured': 'Featured Courses',
    'courses.mostPopular': 'Most Popular Courses',
    'courses.description': 'Discover our most popular courses designed by industry experts',
    'courses.enrollNow': 'Enroll Now',
    'courses.viewAll': 'View All Courses',
    'courses.allAvailable': 'All Courses Available',
    'courses.masterEmbedded': 'Master Embedded',
    'courses.systemsIoT': 'Systems & IoT',
    'courses.discover': 'Discover comprehensive courses in embedded systems, IoT, and programming. Start your journey from beginner to professional level.',
    'courses.searchPlaceholder': 'Search courses...',
    'courses.category': 'Category:',
    'courses.level': 'Level:',
    'courses.found': 'Found',
    'courses.course': 'Course',
    'courses.courses': 'Courses',
    'courses.clearFilters': 'Clear Filters',
    'courses.noCourses': 'No courses found',
    'courses.adjustSearch': 'Try adjusting your search criteria or browse all courses',
    'courses.viewAllCourses': 'View All Courses',
    
    // Features
    'features.whyChoose': 'Why Choose Us?',
    'features.title': 'Industry-Standard Learning Platform',
    'features.description': 'Master embedded systems with our comprehensive, hands-on curriculum designed by industry professionals. From basic concepts to advanced real-world applications.',
    'features.handsOn': 'Hands-on Projects',
    'features.handsOnDesc': 'Build real embedded systems projects from day one',
    'features.industryTools': 'Industry-Standard Tools',
    'features.industryToolsDesc': 'Learn with the same tools used by professionals',
    'features.expertInstructors': 'Expert Instructors',
    'features.expertInstructorsDesc': 'Learn from experienced embedded systems engineers',
    'features.certification': 'Industry Certification',
    'features.certificationDesc': 'Get recognized certificates that employers value. All courses align with industry standards and best practices.',
    
    // Stats
    'stats.activeStudents': 'Active Students',
    'stats.coursesAvailable': 'Courses Available',
    'stats.averageRating': 'Average Rating',
    'stats.successRate': 'Success Rate',
    
    // Course Categories
    'category.embeddedC': 'Embedded C',
    'category.arduino': 'Arduino',
    'category.iot': 'IoT Systems',
    'category.automotive': 'Automotive',
    'category.all': 'All',
    
    // Course Levels
    'level.beginner': 'Beginner',
    'level.intermediate': 'Intermediate',
    'level.advanced': 'Advanced',
    'level.all': 'All',
    
    // Common
    'common.students': 'students',
    'common.weeks': 'weeks',
    'common.readMore': 'Read More',
    'common.learnMore': 'Learn More',
    'common.home': 'Home',
    'common.addToCart': 'Add to Cart',
    'common.enrollNow': 'Enroll Now',
    'common.inStock': 'In Stock',
    'common.outOfStock': 'Out of Stock',
    'common.reviews': 'reviews',
    
    // Professional Pack
    'pack.title': 'Professional Pack',
    'pack.careerPaths': 'Complete Career Paths',
    'pack.description': 'Comprehensive learning tracks designed for specific engineering roles. Master multiple technologies in focused career paths.',
    
    // Footer
    'footer.description': 'Empowering the next generation of embedded systems developers with practical, industry-focused education.',
    'footer.courses': 'Courses',
    'footer.company': 'Company',
    'footer.resources': 'Developer Resources',
    'footer.aboutUs': 'About Us',
    'footer.contact': 'Contact',
    'footer.blog': 'Blog',
    'footer.careers': 'Careers',
    'footer.docs': 'Documentation',
    'footer.api': 'API Reference',
    'footer.community': 'Community',
    'footer.support': 'Support',
    'footer.copyright': '2024 Embedded School. Open source education platform.',
    'footer.operational': 'All systems operational',
    'footer.arduinoProgramming': 'Arduino Programming',
    'footer.embeddedC': 'Embedded C',
    'footer.iotSystems': 'IoT Systems',
    'footer.automotiveElectronics': 'Automotive Electronics',
    
    // About Page
    'about.title': 'Empowering the Next Generation of',
    'about.titleHighlight': 'Embedded Engineers',
    'about.description': 'Founded in Moldova with a vision to democratize embedded systems education across Eastern Europe. We bridge the gap between academic theory and industry practice.',
    'about.missionTitle': 'Building the Future of Embedded Education',
    'about.missionText1': 'To provide world-class embedded systems education that prepares students for successful careers in the rapidly evolving technology landscape. We believe that quality education should be accessible to everyone, regardless of their background.',
    'about.missionText2': 'Since our founding in 2019, we\'ve been committed to creating practical, industry-relevant courses that give our students the skills they need to excel in embedded systems development, IoT, and automotive electronics.',
    'about.joinMission': 'Join Our Mission',
    'about.valuesTitle': 'What Drives Us Forward',
    'about.valuesSubtitle': 'The principles that guide everything we do at Embedded School',
    'about.teamTitle': 'Expert Developers & Educators',
    'about.teamSubtitle': 'Industry professionals with decades of combined experience in embedded systems',
    'about.partnersTitle': 'Trusted by Leading Companies',
    'about.partnersSubtitle': 'Collaborating with leading technology companies to provide real-world experience',
    'about.ctaTitle': 'Ready to Join Our Community?',
    'about.ctaSubtitle': 'Become part of a growing network of embedded systems professionals and enthusiasts.',
    'about.startLearning': 'Start Learning Today',
    'about.contactTeam': 'Contact Our Team',
    
    // Contact Page
    'contact.title': 'We\'re Here to',
    'contact.titleHighlight': 'Help You Succeed',
    'contact.description': 'Have questions about our courses? Need guidance on your embedded systems journey? Our team of experts is ready to assist you every step of the way.',
    'contact.mainOffice': 'Main Office',
    'contact.phoneNumbers': 'Phone Numbers',
    'contact.emailSupport': 'Email Support',
    'contact.officeHours': 'Office Hours',
    'contact.sendMessage': 'Send us a Message',
    'contact.fullName': 'Full Name',
    'contact.emailAddress': 'Email Address',
    'contact.subject': 'Subject',
    'contact.message': 'Message',
    'contact.sendButton': 'Send Message',
    'contact.sending': 'Sending...',
    'contact.needHelp': 'Need Immediate Help?',
    'contact.callUs': 'Call us directly',
    'contact.emailUs': 'Email support',
    'contact.browseCourses': 'Browse courses',
    'contact.findPerfectCourse': 'Find the perfect course for you',
    'contact.faqTitle': 'Frequently Asked Questions',
    'contact.faqSubtitle': 'Quick answers to common questions about our courses and services',
    
    // Trainers Page
    'trainers.title': 'Meet Our',
    'trainers.titleHighlight': 'Expert Trainers',
    'trainers.description': 'Learn from industry professionals with years of real-world experience in embedded systems, IoT development, and cutting-edge technology solutions.',
    'trainers.studentsTaught': 'Students Taught',
    'trainers.averageRating': 'Average Rating',
    'trainers.hoursExperience': 'Hours Experience',
    'trainers.yourMentors': 'Your Learning Mentors',
    'trainers.mentorsDescription': 'Expert embedded systems engineers ready to guide your journey',
    'trainers.viewProfile': 'View Profile',
    'trainers.requestOneToOne': 'Request One-to-One',
    'trainers.expertise': 'Expertise',
    'trainers.specialties': 'Specialties',
    'trainers.students': 'students',
    'trainers.yearsCombinedExp': 'Years Combined Experience',
    'trainers.industryProjects': 'Industry Projects',
    'trainers.studentsMentored': 'Students Mentored',
    'trainers.readyToLearn': 'Ready to Learn from the Best?',
    'trainers.readyDescription': 'Join thousands of students who have advanced their careers with our expert trainers. Get personalized mentorship and hands-on guidance.',
    'trainers.browseAllCourses': 'Browse All Courses',
    'trainers.scheduleConsultation': 'Schedule Consultation',
    'trainers.becomeTrainer': 'Become a',
    'trainers.becomeTrainerHighlight': 'Trainer at Engineers Factory',
    'trainers.becomeTrainerDescription': 'Are you an experienced embedded systems engineer or IoT specialist? Join our team of expert trainers and help shape the next generation of engineers. Share your knowledge and make a meaningful impact.',
    'trainers.flexibleTeaching': 'Flexible Teaching',
    'trainers.flexibleDescription': 'Set your own schedule and teach from anywhere',
    'trainers.expertRecognition': 'Expert Recognition',
    'trainers.recognitionDescription': 'Build your reputation in the embedded systems community',
    'trainers.competitivePay': 'Competitive Pay',
    'trainers.payDescription': 'Earn competitive rates for sharing your expertise',
    'trainers.requirements': 'Requirements',
    'trainers.yearsExperience': 'years of industry experience',
    'trainers.applyNow': 'Apply Now',
    
    // Hardware Page
    'hardware.title': 'Premium Development',
    'hardware.titleHighlight': 'Hardware & Boards',
    'hardware.description': 'Professional-grade development boards and microcontrollers for your embedded projects.',
    'hardware.shopNow': 'Shop Now',
    'hardware.browseCategories': 'Browse Categories',
    'hardware.featuredProducts': 'Featured Products',
    'hardware.professionalBoards': 'Professional Development Boards',
    'hardware.boardsDescription': 'Hand-picked selection of the best microcontrollers and development platforms',
    'hardware.addToCart': 'Add to Cart',
    'hardware.outOfStock': 'Out of Stock',
    'hardware.inStock': 'In Stock',
    'hardware.keySpecs': 'Key Specifications:',
    'hardware.whyBuyFromUs': 'Why Buy From Us?',
    'hardware.trustedWorldwide': 'Trusted by Developers Worldwide',
    'hardware.serviceDescription': 'Professional service and support for all your embedded development needs',
    'hardware.qualityGuaranteed': 'Quality Guaranteed',
    'hardware.qualityDescription': 'All boards tested and verified before shipping',
    'hardware.fastShipping': 'Fast Shipping',
    'hardware.shippingDescription': 'Same-day processing with 2-3 day delivery',
    'hardware.technicalSupport': 'Technical Support',
    'hardware.supportDescription': 'Expert help with setup and troubleshooting',
    'hardware.allBoards': 'All Boards',
    
    // Documentation Page
    'docs.title': 'Everything You Need to',
    'docs.titleHighlight': 'Succeed',
    'docs.description': 'Comprehensive guides, tutorials, and technical documentation to help you master embedded systems development.',
    'docs.searchPlaceholder': 'Search documentation...',
    'docs.communityForum': 'Community Forum',
    'docs.communityDescription': 'Join discussions with other students',
    'docs.technicalResources': 'Technical Resources',
    'docs.resourcesDescription': 'Hardware and tools documentation',
    'docs.gettingStarted': 'Getting Started',
    'docs.courseGuides': 'Course Guides',
    'docs.technicalReference': 'Technical Reference',
    'docs.toolsSetup': 'Tools & Setup',
    'docs.faqs': 'FAQs',
    'docs.noResults': 'No results found',
    'docs.adjustSearch': 'Try adjusting your search or filters',
    'docs.clearFilters': 'Clear Filters',
    'docs.stillQuestions': 'Still Have Questions?',
    'docs.supportDescription': 'Our support team is here to help. Get in touch and we\'ll respond as quickly as possible.',
    'docs.contactSupport': 'Contact Support',
    'docs.joinCommunity': 'Join Community',
    
    // Junior Program Page
    'junior.weekend': 'Weekend School for Juniors',
    'junior.title': 'Build',
    'junior.titleHighlight': 'Rockets of the Future',
    'junior.subtitle': 'For Young Innovators Aged 12-18 • Weekend Classes • Hands-On Tech Projects • Future Career Skills',
    'junior.enrollNow': 'Enroll Now - Limited Spots!',
    'junior.viewCurriculum': 'View Curriculum',
    'junior.studentsTrained': 'Students Trained',
    'junior.completionRate': 'Completion Rate',
    'junior.realProjects': 'Real Projects',
    'junior.parentRating': 'Parent Rating',
    'junior.whyChoose': 'Why Choose Our Junior Program?',
    'junior.whyDescription': 'We transform young minds into tech innovators through project-based learning, industry mentorship, and cutting-edge technology exposure.',
    'junior.spacetech': 'Space Technology',
    'junior.spacetechDesc': 'Learn about satellites, rockets, and space exploration systems',
    'junior.aiRobotics': 'AI & Robotics',
    'junior.aiDesc': 'Build and program intelligent robots with machine learning',
    'junior.gameDev': 'Game Development',
    'junior.gameDevDesc': 'Create your own video games and interactive experiences',
    'junior.mobileApps': 'Mobile Apps',
    'junior.mobileDesc': 'Develop apps that control robots and IoT devices',
  },
  ro: {
    // Navigation
    'nav.courses': 'Cursuri',
    'nav.about': 'Despre',
    'nav.trainers': 'Instructori',
    'nav.blog': 'Blog',
    'nav.hardware': 'Hardware',
    'nav.contact': 'Contact',
    'nav.login': 'Conectare',
    'nav.getStarted': 'Începe Acum',
    
    // Hero Section
    'hero.title': 'Fabrica de Ingineri - Școala de Sisteme Înglobate',
    'hero.subtitle': 'Construiește-ți Viitorul',
    'hero.description': 'Alătură-te miilor de studenți care stăpânesc tehnologia de vârf prin cursuri practice în IoT, sisteme înglobate și multe altele.',
    'hero.startLearning': 'Începe să Înveți Astăzi',
    'hero.watchDemo': 'Vizionează Demo',
    'hero.satisfaction': 'Rata de Satisfacție',
    'hero.activeStudents': 'Studenți Activi',
    'hero.expertCourses': 'Cursuri de Expert',
    
    // Featured Courses
    'courses.featured': 'Cursuri Recomandate',
    'courses.mostPopular': 'Cele Mai Populare Cursuri',
    'courses.description': 'Descoperă cele mai populare cursuri create de experți din industrie',
    'courses.enrollNow': 'Înscrie-te Acum',
    'courses.viewAll': 'Vezi Toate Cursurile',
    'courses.allAvailable': 'Toate Cursurile Disponibile',
    'courses.masterEmbedded': 'Stăpânește Sistemele',
    'courses.systemsIoT': 'Înglobate & IoT',
    'courses.discover': 'Descoperă cursuri complete de sisteme înglobate, IoT și programare. Începe călătoria ta de la nivel începător la nivel profesional.',
    'courses.searchPlaceholder': 'Caută cursuri...',
    'courses.category': 'Categorie:',
    'courses.level': 'Nivel:',
    'courses.found': 'Găsite',
    'courses.course': 'Curs',
    'courses.courses': 'Cursuri',
    'courses.clearFilters': 'Șterge Filtrele',
    'courses.noCourses': 'Niciun curs găsit',
    'courses.adjustSearch': 'Încearcă să ajustezi criteriile de căutare sau vezi toate cursurile',
    'courses.viewAllCourses': 'Vezi Toate Cursurile',
    
    // Features
    'features.whyChoose': 'De Ce Să Ne Alegi?',
    'features.title': 'Platformă de Învățare Conform Standardelor Industriei',
    'features.description': 'Stăpânește sistemele înglobate cu curriculum-ul nostru cuprinzător și practic, conceput de profesioniști din industrie. De la concepte de bază la aplicații avansate din lumea reală.',
    'features.handsOn': 'Proiecte Practice',
    'features.handsOnDesc': 'Construiește proiecte reale de sisteme înglobate din prima zi',
    'features.industryTools': 'Instrumente Standard din Industrie',
    'features.industryToolsDesc': 'Învață cu aceleași instrumente folosite de profesioniști',
    'features.expertInstructors': 'Instructori Experți',
    'features.expertInstructorsDesc': 'Învață de la ingineri experimentați în sisteme înglobate',
    'features.certification': 'Certificare din Industrie',
    'features.certificationDesc': 'Obține certificate recunoscute care sunt apreciate de angajatori. Toate cursurile se aliniază cu standardele și practicile din industrie.',
    
    // Stats
    'stats.activeStudents': 'Studenți Activi',
    'stats.coursesAvailable': 'Cursuri Disponibile',
    'stats.averageRating': 'Rating Mediu',
    'stats.successRate': 'Rata de Succes',
    
    // Course Categories
    'category.embeddedC': 'C Înglobat',
    'category.arduino': 'Arduino',
    'category.iot': 'Sisteme IoT',
    'category.automotive': 'Automotive',
    'category.all': 'Toate',
    
    // Course Levels
    'level.beginner': 'Începător',
    'level.intermediate': 'Intermediar',
    'level.advanced': 'Avansat',
    'level.all': 'Toate',
    
    // Common
    'common.students': 'studenți',
    'common.weeks': 'săptămâni',
    'common.readMore': 'Citește Mai Mult',
    'common.learnMore': 'Află Mai Mult',
    'common.home': 'Acasă',
    'common.addToCart': 'Adaugă în Coș',
    'common.enrollNow': 'Înscrie-te Acum',
    'common.inStock': 'În Stoc',
    'common.outOfStock': 'Stoc Epuizat',
    'common.reviews': 'recenzii',
    
    // Professional Pack
    'pack.title': 'Pachet Profesional',
    'pack.careerPaths': 'Trasee de Carieră Complete',
    'pack.description': 'Trasee de învățare cuprinzătoare concepute pentru roluri specifice de inginerie. Stăpânește tehnologii multiple în trasee de carieră focalizate.',
    
    // Footer
    'footer.description': 'Împuternicim noua generație de dezvoltatori de sisteme înglobate cu educație practică, orientată către industrie.',
    'footer.courses': 'Cursuri',
    'footer.company': 'Companie',
    'footer.resources': 'Resurse pentru Dezvoltatori',
    'footer.aboutUs': 'Despre Noi',
    'footer.contact': 'Contact',
    'footer.blog': 'Blog',
    'footer.careers': 'Cariere',
    'footer.docs': 'Documentație',
    'footer.api': 'Referință API',
    'footer.community': 'Comunitate',
    'footer.support': 'Suport',
    'footer.copyright': '2024 Embedded School. Platformă de educație open source.',
    'footer.operational': 'Toate sistemele operaționale',
    'footer.arduinoProgramming': 'Programare Arduino',
    'footer.embeddedC': 'C Înglobat',
    'footer.iotSystems': 'Sisteme IoT',
    'footer.automotiveElectronics': 'Electronică Auto',
    
    // About Page
    'about.title': 'Împuternicim Noua Generație de',
    'about.titleHighlight': 'Ingineri Înglobați',
    'about.description': 'Fondată în Moldova cu viziunea de a democratiza educația sistemelor înglobate în Europa de Est. Comblăm diferența între teoria academică și practica industrială.',
    'about.missionTitle': 'Construim Viitorul Educației Înglobate',
    'about.missionText1': 'Să oferim educație de clasă mondială în sisteme înglobate care pregătește studenții pentru cariere de succes în peisajul tehnologic în rapidă evoluție. Credem că educația de calitate ar trebui să fie accesibilă tuturor, indiferent de background.',
    'about.missionText2': 'Din 2019, ne-am angajat să creăm cursuri practice, relevante pentru industrie, care le oferă studenților noștri abilitățile necesare pentru a excela în dezvoltarea sistemelor înglobate, IoT și electronică auto.',
    'about.joinMission': 'Alătură-te Misiunii Noastre',
    'about.valuesTitle': 'Ce Ne Conduce Înainte',
    'about.valuesSubtitle': 'Principiile care ghidează tot ceea ce facem la Embedded School',
    'about.teamTitle': 'Dezvoltatori și Educatori Experți',
    'about.teamSubtitle': 'Profesioniști din industrie cu decenii de experiență combinată în sisteme înglobate',
    'about.partnersTitle': 'De Încredere pentru Companii de Top',
    'about.partnersSubtitle': 'Colaborăm cu companii tehnologice de top pentru a oferi experiență din lumea reală',
    'about.ctaTitle': 'Gata să Te Alături Comunității Noastre?',
    'about.ctaSubtitle': 'Devino parte dintr-o rețea în creștere de profesioniști și entuziaști ai sistemelor înglobate.',
    'about.startLearning': 'Începe să Înveți Astăzi',
    'about.contactTeam': 'Contactează Echipa Noastră',
    
    // Contact Page
    'contact.title': 'Suntem Aici să',
    'contact.titleHighlight': 'Te Ajutăm să Reușești',
    'contact.description': 'Ai întrebări despre cursurile noastre? Ai nevoie de îndrumare în călătoria ta cu sisteme înglobate? Echipa noastră de experți este gata să te asiste la fiecare pas.',
    'contact.mainOffice': 'Biroul Principal',
    'contact.phoneNumbers': 'Numere de Telefon',
    'contact.emailSupport': 'Suport Email',
    'contact.officeHours': 'Orele de Birou',
    'contact.sendMessage': 'Trimite-ne un Mesaj',
    'contact.fullName': 'Nume Complet',
    'contact.emailAddress': 'Adresa de Email',
    'contact.subject': 'Subiect',
    'contact.message': 'Mesaj',
    'contact.sendButton': 'Trimite Mesaj',
    'contact.sending': 'Se trimite...',
    'contact.needHelp': 'Ai Nevoie de Ajutor Imediat?',
    'contact.callUs': 'Sună-ne direct',
    'contact.emailUs': 'Suport email',
    'contact.browseCourses': 'Răsfoiește cursurile',
    'contact.findPerfectCourse': 'Găsește cursul perfect pentru tine',
    'contact.faqTitle': 'Întrebări Frecvente',
    'contact.faqSubtitle': 'Răspunsuri rapide la întrebări comune despre cursurile și serviciile noastre',
    
    // Trainers Page
    'trainers.title': 'Cunoaște',
    'trainers.titleHighlight': 'Instructorii Noștri Experți',
    'trainers.description': 'Învață de la profesioniști din industrie cu ani de experiență reală în sisteme înglobate, dezvoltare IoT și soluții tehnologice de ultimă oră.',
    'trainers.studentsTaught': 'Studenți Predați',
    'trainers.averageRating': 'Rating Mediu',
    'trainers.hoursExperience': 'Ore de Experiență',
    'trainers.yourMentors': 'Mentorii Tăi de Învățare',
    'trainers.mentorsDescription': 'Ingineri experți în sisteme înglobate gata să-ți ghideze călătoria',
    'trainers.viewProfile': 'Vezi Profilul',
    'trainers.requestOneToOne': 'Solicită Întâlnire Individuală',
    'trainers.expertise': 'Expertiză',
    'trainers.specialties': 'Specializări',
    'trainers.students': 'studenți',
    'trainers.yearsCombinedExp': 'Ani de Experiență Combinată',
    'trainers.industryProjects': 'Proiecte din Industrie',
    'trainers.studentsMentored': 'Studenți Mentorați',
    'trainers.readyToLearn': 'Gata să Înveți de la Cei Mai Buni?',
    'trainers.readyDescription': 'Alătură-te miilor de studenți care și-au avansat carierele cu instructorii noștri experți. Obține mentorat personalizat și îndrumare practică.',
    'trainers.browseAllCourses': 'Răsfoiește Toate Cursurile',
    'trainers.scheduleConsultation': 'Programează Consultație',
    'trainers.becomeTrainer': 'Devino',
    'trainers.becomeTrainerHighlight': 'Instructor la Fabrica de Ingineri',
    'trainers.becomeTrainerDescription': 'Ești un inginer experimentat în sisteme înglobate sau specialist IoT? Alătură-te echipei noastre de instructori experți și ajută-ne să modelăm următoarea generație de ingineri. Împărtășește-ți cunoștințele și fă un impact semnificativ.',
    'trainers.flexibleTeaching': 'Predare Flexibilă',
    'trainers.flexibleDescription': 'Stabilește-ți propriul program și predă de oriunde',
    'trainers.expertRecognition': 'Recunoaștere Expert',
    'trainers.recognitionDescription': 'Construiește-ți reputația în comunitatea sistemelor înglobate',
    'trainers.competitivePay': 'Salarizare Competitivă',
    'trainers.payDescription': 'Câștigă rate competitive pentru împărtășirea expertizei tale',
    'trainers.requirements': 'Cerințe',
    'trainers.yearsExperience': 'ani de experiență în industrie',
    'trainers.applyNow': 'Aplică Acum',
    
    // Hardware Page
    'hardware.title': 'Hardware de Dezvoltare',
    'hardware.titleHighlight': 'Premium & Plăci',
    'hardware.description': 'Plăci de dezvoltare și microcontrolere de calitate profesională pentru proiectele tale înglobate.',
    'hardware.shopNow': 'Cumpără Acum',
    'hardware.browseCategories': 'Răsfoiește Categorii',
    'hardware.featuredProducts': 'Produse Recomandate',
    'hardware.professionalBoards': 'Plăci de Dezvoltare Profesionale',
    'hardware.boardsDescription': 'Selecție aleasă a celor mai bune microcontrolere și platforme de dezvoltare',
    'hardware.addToCart': 'Adaugă în Coș',
    'hardware.outOfStock': 'Stoc Epuizat',
    'hardware.inStock': 'În Stoc',
    'hardware.keySpecs': 'Specificații Cheie:',
    'hardware.whyBuyFromUs': 'De Ce Să Cumperi de la Noi?',
    'hardware.trustedWorldwide': 'De Încredere pentru Dezvoltatori din Întreaga Lume',
    'hardware.serviceDescription': 'Servicii și suport profesional pentru toate nevoile tale de dezvoltare înglobată',
    'hardware.qualityGuaranteed': 'Calitate Garantată',
    'hardware.qualityDescription': 'Toate plăcile sunt testate și verificate înainte de expediere',
    'hardware.fastShipping': 'Livrare Rapidă',
    'hardware.shippingDescription': 'Procesare în aceeași zi cu livrare în 2-3 zile',
    'hardware.technicalSupport': 'Suport Tehnic',
    'hardware.supportDescription': 'Ajutor expert pentru configurare și depanare',
    'hardware.allBoards': 'Toate Plăcile',
    
    // Documentation Page
    'docs.title': 'Tot Ce Ai Nevoie Pentru a',
    'docs.titleHighlight': 'Reuși',
    'docs.description': 'Ghiduri cuprinzătoare, tutoriale și documentație tehnică pentru a te ajuta să stăpânești dezvoltarea sistemelor înglobate.',
    'docs.searchPlaceholder': 'Caută în documentație...',
    'docs.communityForum': 'Forum Comunitate',
    'docs.communityDescription': 'Alătură-te discuțiilor cu alți studenți',
    'docs.technicalResources': 'Resurse Tehnice',
    'docs.resourcesDescription': 'Documentație hardware și instrumente',
    'docs.gettingStarted': 'Început',
    'docs.courseGuides': 'Ghiduri Cursuri',
    'docs.technicalReference': 'Referință Tehnică',
    'docs.toolsSetup': 'Instalare Instrumente',
    'docs.faqs': 'Întrebări Frecvente',
    'docs.noResults': 'Niciun rezultat găsit',
    'docs.adjustSearch': 'Încearcă să ajustezi căutarea sau filtrele',
    'docs.clearFilters': 'Șterge Filtrele',
    'docs.stillQuestions': 'Mai Ai Întrebări?',
    'docs.supportDescription': 'Echipa noastră de suport este aici să te ajute. Contactează-ne și vom răspunde cât mai repede posibil.',
    'docs.contactSupport': 'Contactează Suportul',
    'docs.joinCommunity': 'Alătură-te Comunității',
    
    // Junior Program Page
    'junior.weekend': 'Școală de Weekend pentru Juniori',
    'junior.title': 'Construiește',
    'junior.titleHighlight': 'Rachetele Viitorului',
    'junior.subtitle': 'Pentru Tineri Inovatori cu Vârste 12-18 • Cursuri de Weekend • Proiecte Tech Hands-On • Abilități pentru Cariera Viitoare',
    'junior.enrollNow': 'Înscrie-te Acum - Locuri Limitate!',
    'junior.viewCurriculum': 'Vezi Curriculum',
    'junior.studentsTrained': 'Studenți Instruiți',
    'junior.completionRate': 'Rata de Finalizare',
    'junior.realProjects': 'Proiecte Reale',
    'junior.parentRating': 'Rating Părinți',
    'junior.whyChoose': 'De Ce Să Alegi Programul Nostru Junior?',
    'junior.whyDescription': 'Transformăm minți tinere în inovatori tech prin învățare bazată pe proiecte, mentorat din industrie și expunere la tehnologie de ultimă oră.',
    'junior.spacetech': 'Tehnologie Spațială',
    'junior.spacetechDesc': 'Învață despre sateliți, rachete și sisteme de explorare spațială',
    'junior.aiRobotics': 'AI & Robotică',
    'junior.aiDesc': 'Construiește și programează roboți inteligenți cu învățare automată',
    'junior.gameDev': 'Dezvoltare Jocuri',
    'junior.gameDevDesc': 'Creează propriile tale jocuri video și experiențe interactive',
    'junior.mobileApps': 'Aplicații Mobile',
    'junior.mobileDesc': 'Dezvoltă aplicații care controlează roboți și dispozitive IoT',
  },
  ru: {
    // Navigation
    'nav.courses': 'Курсы',
    'nav.about': 'О нас',
    'nav.trainers': 'Инструкторы',
    'nav.blog': 'Блог',
    'nav.hardware': 'Оборудование',
    'nav.contact': 'Контакты',
    'nav.login': 'Войти',
    'nav.getStarted': 'Начать',
    
    // Hero Section
    'hero.title': 'Фабрика Инженеров - Школа Встраиваемых Систем',
    'hero.subtitle': 'Построй Свое Будущее',
    'hero.description': 'Присоединяйтесь к тысячам студентов, осваивающих передовые технологии через практические курсы по IoT, встраиваемым системам и многому другому.',
    'hero.startLearning': 'Начать Обучение Сегодня',
    'hero.watchDemo': 'Смотреть Демо',
    'hero.satisfaction': 'Уровень Удовлетворенности',
    'hero.activeStudents': 'Активные Студенты',
    'hero.expertCourses': 'Экспертные Курсы',
    
    // Featured Courses
    'courses.featured': 'Рекомендуемые Курсы',
    'courses.mostPopular': 'Самые Популярные Курсы',
    'courses.description': 'Откройте для себя наши самые популярные курсы, созданные отраслевыми экспертами',
    'courses.enrollNow': 'Записаться Сейчас',
    'courses.viewAll': 'Посмотреть Все Курсы',
    'courses.allAvailable': 'Все Доступные Курсы',
    'courses.masterEmbedded': 'Освойте Встраиваемые',
    'courses.systemsIoT': 'Системы и IoT',
    'courses.discover': 'Откройте для себя полные курсы по встраиваемым системам, IoT и программированию. Начните свой путь от новичка до профессионального уровня.',
    'courses.searchPlaceholder': 'Поиск курсов...',
    'courses.category': 'Категория:',
    'courses.level': 'Уровень:',
    'courses.found': 'Найдено',
    'courses.course': 'Курс',
    'courses.courses': 'Курсы',
    'courses.clearFilters': 'Очистить Фильтры',
    'courses.noCourses': 'Курсы не найдены',
    'courses.adjustSearch': 'Попробуйте изменить критерии поиска или просмотрите все курсы',
    'courses.viewAllCourses': 'Посмотреть Все Курсы',
    
    // Features
    'features.whyChoose': 'Почему Мы?',
    'features.title': 'Платформа Обучения Промышленных Стандартов',
    'features.description': 'Овладейте встраиваемыми системами с нашей всесторонней практической программой, разработанной профессионалами отрасли. От базовых концепций до продвинутых реальных приложений.',
    'features.handsOn': 'Практические Проекты',
    'features.handsOnDesc': 'Создавайте реальные проекты встраиваемых систем с первого дня',
    'features.industryTools': 'Промышленные Инструменты',
    'features.industryToolsDesc': 'Учитесь с теми же инструментами, которые используют профессионалы',
    'features.expertInstructors': 'Экспертные Инструкторы',
    'features.expertInstructorsDesc': 'Учитесь у опытных инженеров встраиваемых систем',
    'features.certification': 'Промышленная Сертификация',
    'features.certificationDesc': 'Получите признанные сертификаты, которые ценят работодатели. Все курсы соответствуют отраслевым стандартам и лучшим практикам.',
    
    // Stats
    'stats.activeStudents': 'Активные Студенты',
    'stats.coursesAvailable': 'Доступные Курсы',
    'stats.averageRating': 'Средний Рейтинг',
    'stats.successRate': 'Уровень Успеха',
    
    // Course Categories
    'category.embeddedC': 'Встраиваемый C',
    'category.arduino': 'Arduino',
    'category.iot': 'IoT Системы',
    'category.automotive': 'Автомобильные',
    'category.all': 'Все',
    
    // Course Levels
    'level.beginner': 'Начинающий',
    'level.intermediate': 'Средний',
    'level.advanced': 'Продвинутый',
    'level.all': 'Все',
    
    // Common
    'common.students': 'студенты',
    'common.weeks': 'недели',
    'common.readMore': 'Читать Далее',
    'common.learnMore': 'Узнать Больше',
    'common.home': 'Главная',
    'common.addToCart': 'Добавить в Корзину',
    'common.enrollNow': 'Записаться Сейчас',
    'common.inStock': 'В Наличии',
    'common.outOfStock': 'Нет в Наличии',
    'common.reviews': 'отзывы',
    
    // Professional Pack
    'pack.title': 'Профессиональный Пакет',
    'pack.careerPaths': 'Полные Карьерные Пути',
    'pack.description': 'Всеобъемлющие учебные треки, разработанные для конкретных инженерных ролей. Освойте несколько технологий в целенаправленных карьерных путях.',
    
    // Footer
    'footer.description': 'Расширяем возможности следующего поколения разработчиков встраиваемых систем с практическим, ориентированным на отрасль образованием.',
    'footer.courses': 'Курсы',
    'footer.company': 'Компания',
    'footer.resources': 'Ресурсы для Разработчиков',
    'footer.aboutUs': 'О Нас',
    'footer.contact': 'Контакты',
    'footer.blog': 'Блог',
    'footer.careers': 'Карьера',
    'footer.docs': 'Документация',
    'footer.api': 'Справочник API',
    'footer.community': 'Сообщество',
    'footer.support': 'Поддержка',
    'footer.copyright': '2024 Embedded School. Образовательная платформа с открытым исходным кодом.',
    'footer.operational': 'Все системы работают',
    'footer.arduinoProgramming': 'Программирование Arduino',
    'footer.embeddedC': 'Встраиваемый C',
    'footer.iotSystems': 'IoT Системы',
    'footer.automotiveElectronics': 'Автомобильная Электроника',
    
    // About Page
    'about.title': 'Расширяем Возможности Следующего Поколения',
    'about.titleHighlight': 'Встраиваемых Инженеров',
    'about.description': 'Основана в Молдове с видением демократизировать образование встраиваемых систем в Восточной Европе. Мы соединяем академическую теорию с промышленной практикой.',
    'about.missionTitle': 'Строим Будущее Встраиваемого Образования',
    'about.missionText1': 'Предоставлять образование мирового уровня по встраиваемым системам, которое готовит студентов к успешной карьере в быстро развивающемся технологическом ландшафте. Мы верим, что качественное образование должно быть доступно всем, независимо от их происхождения.',
    'about.missionText2': 'С момента нашего основания в 2019 году мы стремились создавать практические, актуальные для индустрии курсы, которые дают нашим студентам навыки, необходимые для успеха в разработке встраиваемых систем, IoT и автомобильной электронике.',
    'about.joinMission': 'Присоединитесь к Нашей Миссии',
    'about.valuesTitle': 'Что Движет Нас Вперед',
    'about.valuesSubtitle': 'Принципы, которые направляют все, что мы делаем в Embedded School',
    'about.teamTitle': 'Эксперты-Разработчики и Преподаватели',
    'about.teamSubtitle': 'Профессионалы индустрии с десятилетиями общего опыта во встраиваемых системах',
    'about.partnersTitle': 'Доверяют Ведущие Компании',
    'about.partnersSubtitle': 'Сотрудничаем с ведущими технологическими компаниями для предоставления реального опыта',
    'about.ctaTitle': 'Готовы Присоединиться к Нашему Сообществу?',
    'about.ctaSubtitle': 'Станьте частью растущей сети профессионалов и энтузиастов встраиваемых систем.',
    'about.startLearning': 'Начать Обучение Сегодня',
    'about.contactTeam': 'Связаться с Командой',
    
    // Contact Page
    'contact.title': 'Мы Здесь, Чтобы',
    'contact.titleHighlight': 'Помочь Вам Преуспеть',
    'contact.description': 'Есть вопросы о наших курсах? Нужны советы по вашему пути во встраиваемых системах? Наша команда экспертов готова помочь вам на каждом шагу.',
    'contact.mainOffice': 'Главный Офис',
    'contact.phoneNumbers': 'Телефонные Номера',
    'contact.emailSupport': 'Поддержка Email',
    'contact.officeHours': 'Часы Работы Офиса',
    'contact.sendMessage': 'Отправьте нам Сообщение',
    'contact.fullName': 'Полное Имя',
    'contact.emailAddress': 'Адрес Электронной Почты',
    'contact.subject': 'Тема',
    'contact.message': 'Сообщение',
    'contact.sendButton': 'Отправить Сообщение',
    'contact.sending': 'Отправка...',
    'contact.needHelp': 'Нужна Немедленная Помощь?',
    'contact.callUs': 'Позвоните нам напрямую',
    'contact.emailUs': 'Поддержка по email',
    'contact.browseCourses': 'Просмотреть курсы',
    'contact.findPerfectCourse': 'Найдите идеальный курс для себя',
    'contact.faqTitle': 'Часто Задаваемые Вопросы',
    'contact.faqSubtitle': 'Быстрые ответы на распространенные вопросы о наших курсах и услугах',
    
    // Trainers Page
    'trainers.title': 'Познакомьтесь с',
    'trainers.titleHighlight': 'Нашими Экспертными Инструкторами',
    'trainers.description': 'Учитесь у профессионалов индустрии с многолетним реальным опытом во встраиваемых системах, разработке IoT и передовых технологических решениях.',
    'trainers.studentsTaught': 'Обученных Студентов',
    'trainers.averageRating': 'Средний Рейтинг',
    'trainers.hoursExperience': 'Часов Опыта',
    'trainers.yourMentors': 'Ваши Учебные Наставники',
    'trainers.mentorsDescription': 'Эксперты-инженеры встраиваемых систем готовы направить ваш путь',
    'trainers.viewProfile': 'Посмотреть Профиль',
    'trainers.requestOneToOne': 'Запросить Индивидуальную Встречу',
    'trainers.expertise': 'Опыт',
    'trainers.specialties': 'Специализации',
    'trainers.students': 'студенты',
    'trainers.yearsCombinedExp': 'Лет Общего Опыта',
    'trainers.industryProjects': 'Промышленных Проектов',
    'trainers.studentsMentored': 'Менторских Студентов',
    'trainers.readyToLearn': 'Готовы Учиться у Лучших?',
    'trainers.readyDescription': 'Присоединяйтесь к тысячам студентов, которые продвинули свою карьеру с нашими экспертными инструкторами. Получите персонализированное наставничество и практическое руководство.',
    'trainers.browseAllCourses': 'Просмотреть Все Курсы',
    'trainers.scheduleConsultation': 'Запланировать Консультацию',
    'trainers.becomeTrainer': 'Станьте',
    'trainers.becomeTrainerHighlight': 'Инструктором в Фабрике Инженеров',
    'trainers.becomeTrainerDescription': 'Вы опытный инженер встраиваемых систем или специалист IoT? Присоединяйтесь к нашей команде экспертных инструкторов и помогите сформировать следующее поколение инженеров. Делитесь своими знаниями и оказывайте значимое влияние.',
    'trainers.flexibleTeaching': 'Гибкое Преподавание',
    'trainers.flexibleDescription': 'Установите свой собственный график и преподавайте откуда угодно',
    'trainers.expertRecognition': 'Экспертное Признание',
    'trainers.recognitionDescription': 'Создайте свою репутацию в сообществе встраиваемых систем',
    'trainers.competitivePay': 'Конкурентная Оплата',
    'trainers.payDescription': 'Зарабатывайте конкурентные ставки за обмен опытом',
    'trainers.requirements': 'Требования',
    'trainers.yearsExperience': 'лет отраслевого опыта',
    'trainers.applyNow': 'Подать Заявку Сейчас',
    
    // Hardware Page
    'hardware.title': 'Премиальное Оборудование',
    'hardware.titleHighlight': 'для Разработки и Платы',
    'hardware.description': 'Профессиональные платы разработки и микроконтроллеры для ваших встраиваемых проектов.',
    'hardware.shopNow': 'Купить Сейчас',
    'hardware.browseCategories': 'Просмотреть Категории',
    'hardware.featuredProducts': 'Рекомендуемые Продукты',
    'hardware.professionalBoards': 'Профессиональные Платы Разработки',
    'hardware.boardsDescription': 'Тщательно отобранный выбор лучших микроконтроллеров и платформ разработки',
    'hardware.addToCart': 'Добавить в Корзину',
    'hardware.outOfStock': 'Нет в Наличии',
    'hardware.inStock': 'В Наличии',
    'hardware.keySpecs': 'Ключевые Характеристики:',
    'hardware.whyBuyFromUs': 'Почему Покупать у Нас?',
    'hardware.trustedWorldwide': 'Доверяют Разработчики по Всему Миру',
    'hardware.serviceDescription': 'Профессиональные услуги и поддержка для всех ваших потребностей в разработке встраиваемых систем',
    'hardware.qualityGuaranteed': 'Гарантия Качества',
    'hardware.qualityDescription': 'Все платы тестируются и проверяются перед отправкой',
    'hardware.fastShipping': 'Быстрая Доставка',
    'hardware.shippingDescription': 'Обработка в тот же день с доставкой 2-3 дня',
    'hardware.technicalSupport': 'Техническая Поддержка',
    'hardware.supportDescription': 'Экспертная помощь в настройке и устранении неполадок',
    'hardware.allBoards': 'Все Платы',
    
    // Documentation Page
    'docs.title': 'Все, Что Вам Нужно для',
    'docs.titleHighlight': 'Успеха',
    'docs.description': 'Всеобъемлющие руководства, учебные пособия и техническая документация, которые помогут вам освоить разработку встраиваемых систем.',
    'docs.searchPlaceholder': 'Поиск в документации...',
    'docs.communityForum': 'Форум Сообщества',
    'docs.communityDescription': 'Присоединяйтесь к обсуждениям с другими студентами',
    'docs.technicalResources': 'Технические Ресурсы',
    'docs.resourcesDescription': 'Документация по оборудованию и инструментам',
    'docs.gettingStarted': 'Начало Работы',
    'docs.courseGuides': 'Руководства по Курсам',
    'docs.technicalReference': 'Технический Справочник',
    'docs.toolsSetup': 'Настройка Инструментов',
    'docs.faqs': 'Часто Задаваемые Вопросы',
    'docs.noResults': 'Результаты не найдены',
    'docs.adjustSearch': 'Попробуйте изменить поиск или фильтры',
    'docs.clearFilters': 'Очистить Фильтры',
    'docs.stillQuestions': 'Остались Вопросы?',
    'docs.supportDescription': 'Наша команда поддержки здесь, чтобы помочь. Свяжитесь с нами, и мы ответим как можно быстрее.',
    'docs.contactSupport': 'Связаться с Поддержкой',
    'docs.joinCommunity': 'Присоединиться к Сообществу',
    
    // Junior Program Page
    'junior.weekend': 'Выходная Школа для Юниоров',
    'junior.title': 'Стройте',
    'junior.titleHighlight': 'Ракеты Будущего',
    'junior.subtitle': 'Для Юных Инноваторов 12-18 Лет • Занятия по Выходным • Практические Технические Проекты • Навыки для Будущей Карьеры',
    'junior.enrollNow': 'Записаться Сейчас - Ограниченные Места!',
    'junior.viewCurriculum': 'Посмотреть Программу',
    'junior.studentsTrained': 'Обученных Студентов',
    'junior.completionRate': 'Уровень Завершения',
    'junior.realProjects': 'Реальных Проектов',
    'junior.parentRating': 'Рейтинг Родителей',
    'junior.whyChoose': 'Почему Выбрать Нашу Юниорскую Программу?',
    'junior.whyDescription': 'Мы превращаем молодые умы в технологических инноваторов через проектное обучение, наставничество из индустрии и знакомство с передовыми технологиями.',
    'junior.spacetech': 'Космические Технологии',
    'junior.spacetechDesc': 'Узнайте о спутниках, ракетах и системах исследования космоса',
    'junior.aiRobotics': 'ИИ и Робототехника',
    'junior.aiDesc': 'Создавайте и программируйте умных роботов с машинным обучением',
    'junior.gameDev': 'Разработка Игр',
    'junior.gameDevDesc': 'Создавайте свои собственные видеоигры и интерактивные опыты',
    'junior.mobileApps': 'Мобильные Приложения',
    'junior.mobileDesc': 'Разрабатывайте приложения, которые управляют роботами и IoT устройствами',
  },
};

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('en');

  useEffect(() => {
    const savedLanguage = localStorage.getItem('language') as Language;
    if (savedLanguage && (savedLanguage === 'en' || savedLanguage === 'ro' || savedLanguage === 'ru')) {
      setLanguage(savedLanguage);
    }
  }, []);

  const changeLanguage = (lang: Language) => {
    setLanguage(lang);
    localStorage.setItem('language', lang);
  };

  const t = (key: string, defaultValue?: string): string => {
    return translations[language][key] || defaultValue || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage: changeLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
